apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: HelloTencent
  name: HelloTencent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HelloTencent
  template:
    metadata:
      labels:
        app: HelloTencent
    spec:
      containers:
        - image: index.docker.io/dongxuny/hellotencent
          imagePullPolicy: Always
          name: hello-tencent
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
