apiVersion: v1
  kind: Service
  metadata:
    name: HelloTencent
    namespace: default   
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 1984
    selector:
      app: HelloTencent
    type: LoadBalancer
